### ISSUE TITLE
Error: Cannot find module 'ws'

### ISSUE THREAD

**Issue by sydneyDK** [shogerr/bluprntr#1]
I have ws installed, but tool indicates it can not find the library.  I have confirmed in the terminal that ws is available and can be run.   As I understand it "ws" is a local webserver.

node server.js
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- /Users/cdk/Downloads/bluprntr-master/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/cdk/Downloads/bluprntr-master/server.js
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.j 
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/cdk/Downloads/bluprntr-master/server.js' ]
}

**Comment by shogerr** [comment]
Can you try running `yarn install` or `npm install` from the project directory if you haven't? It sounds like maybe `npm install ws --global` was used to install the package?

**Comment by sydneyDK** [comment]
Thanks, shogerr.
